// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// **Attenzione: questo file era sbagliato, e per mesi nessuno se n'è accorto.**
///
/// Era stato generato prima che il pacchetto venisse rinominato in
/// `com.trailshare.app`, e conteneva ancora gli appId e il bundle id della
/// vecchia registrazione (`com.trailshare.trailshare_flutter`). Su mobile non
/// faceva danno visibile perché a runtime vincono i file nativi —
/// `google-services.json` e `GoogleService-Info.plist` — che il plugin legge
/// per conto suo: questi valori venivano ignorati.
///
/// È il tipo di errore che non si manifesta finché qualcosa non comincia
/// davvero a usarli, e allora si presenta come un guasto incomprensibile.
///
/// Se un domani si rigenera con `flutterfire configure`, **si verifichi che gli
/// appId corrispondano ai due file nativi** prima di committare.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBsUOXZ_ZgLphPd4VNJy5s8BLAjSrUvHs',
    appId: '1:760969043040:web:a750edfa2c9dcee776f705',
    messagingSenderId: '760969043040',
    projectId: 'trailshare-5334b',
    authDomain: 'trailshare-5334b.firebaseapp.com',
    storageBucket: 'trailshare-5334b.firebasestorage.app',
    measurementId: 'G-FRHDB6C3SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClfCz4n9NPVVopvf0_tx9JCj8bHcZQ87w',
    appId: '1:760969043040:android:5a5dac92738c770876f705',
    messagingSenderId: '760969043040',
    projectId: 'trailshare-5334b',
    storageBucket: 'trailshare-5334b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCto_miE4_c9EfOwDa7NovDI7Jh_0DhSA',
    appId: '1:760969043040:ios:68e32749c97160ea76f705',
    messagingSenderId: '760969043040',
    projectId: 'trailshare-5334b',
    storageBucket: 'trailshare-5334b.firebasestorage.app',
    androidClientId: '760969043040-1ngorkl23ebkn42l7qqnqkke89vc2i7i.apps.googleusercontent.com',
    iosClientId: '760969043040-rebmjpn824dc40gfo8s70k7n96262ud5.apps.googleusercontent.com',
    iosBundleId: 'com.trailshare.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCto_miE4_c9EfOwDa7NovDI7Jh_0DhSA',
    appId: '1:760969043040:ios:68e32749c97160ea76f705',
    messagingSenderId: '760969043040',
    projectId: 'trailshare-5334b',
    storageBucket: 'trailshare-5334b.firebasestorage.app',
    androidClientId: '760969043040-1ngorkl23ebkn42l7qqnqkke89vc2i7i.apps.googleusercontent.com',
    iosClientId: '760969043040-rebmjpn824dc40gfo8s70k7n96262ud5.apps.googleusercontent.com',
    iosBundleId: 'com.trailshare.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSrYbdHg47bDYkOpvLfLtM95qpymT_Sgs',
    appId: '1:760969043040:web:3805d8706194524876f705',
    messagingSenderId: '760969043040',
    projectId: 'trailshare-5334b',
    authDomain: 'trailshare-5334b.firebaseapp.com',
    storageBucket: 'trailshare-5334b.firebasestorage.app',
    measurementId: 'G-4BVWH7M8F0',
  );
}
